Repository flatpak/flatpak, pull requests merged in 2022-08, with the labels that each got.

#4826 Add DeploySideloadCollectionID flatpakref/flatpakrepo key
  common/flatpak-dir-private.h
  common/flatpak-dir.c
  common/flatpak-utils-private.h
  common/flatpak-utils.c
  doc/flatpak-flatpakref.xml
  doc/flatpak-flatpakrepo.xml
  tests/test-repo.sh
Labels: p2p, ready-for-review

#4817 build-export: Proper validation of Exec line in desktop file
  app/flatpak-builtins-build-export.c
Labels: ready-for-review

#5014 app: Add -u alias for --user
  app/flatpak-main.c
  doc/flatpak-config.xml
  doc/flatpak-create-usb.xml
  doc/flatpak-history.xml
  doc/flatpak-info.xml
  doc/flatpak-install.xml
  doc/flatpak-list.xml
  doc/flatpak-make-current.xml
  doc/flatpak-mask.xml
  doc/flatpak-override.xml
  doc/flatpak-pin.xml
  doc/flatpak-remote-add.xml
  doc/flatpak-remote-delete.xml
  doc/flatpak-remote-info.xml
  doc/flatpak-remote-ls.xml
  doc/flatpak-remote-modify.xml
  doc/flatpak-remotes.xml
  doc/flatpak-repair.xml
  doc/flatpak-run.xml
  doc/flatpak-search.xml
  doc/flatpak-uninstall.xml
  doc/flatpak-update.xml
Labels: enhancement, cli

#5005 Update Ukrainian translation
  po/uk.po
Labels: reviewed, i18n

#4958 Add --socket=gpg-agent
  common/flatpak-context-private.h
  common/flatpak-context.c
  common/flatpak-run.c
  doc/flatpak-build-finish.xml
  doc/flatpak-build.xml
  doc/flatpak-override.xml
  doc/flatpak-run.xml
Labels: ready-for-review
