Repository flatpak/flatpak, pull requests merged in 2023-02, with the labels that each got.

#5286 run: Avoid double-free of gpgconf stdout stream
  common/flatpak-run.c
Labels: bug, sandbox, ready-for-review

#5284 utils-http: Avoid deprecation warning with curl >= 7.85.0
  common/flatpak-utils-http.c
Labels: ready-for-review

#5312 Russian translation update
  po/ru.po
Labels: i18n

#5313 update es.po
  po/es.po
Labels: i18n
